---
abstract: 'class builder for memory-efficient objects'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Modern: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Marmoset
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Marmoset:
    file: lib/Marmoset.pm
    version: 0.000_01
  Marmoset::Attribute:
    file: lib/Marmoset.pm
    version: 0.000_01
  Marmoset::Attribute::Field:
    file: lib/Marmoset.pm
    version: 0.000_01
  Marmoset::Attribute::InsideOut:
    file: lib/Marmoset.pm
    version: 0.000_01
  Marmoset::Object:
    file: lib/Marmoset.pm
    version: 0.000_01
recommends:
  Sub::Name: 0
  Type::Utils: 0
requires:
  Eval::TypeTiny: 0
  Exporter::Shiny: 0
  Sub::Accessor::Small: 0
  perl: 5.008003
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Marmoset/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Marmoset
  homepage: https://metacpan.org/release/Marmoset
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-marmoset.git
version: 0.000_01
